### ISSUE TITLE
Release update on Moodle.org

### ISSUE THREAD

**Issue by michael-milette** [cescobedo/moodle-auth_dev#1]
HI @cescobedo ,

I noticed that the bug "Abstract user_login() method must be overridden." when entering an invalid username was fixed about 3 years ago. Would it be possible to update the version available on [moodle.org/plugins](https://moodle.org/plugins/auth_dev) ?

Best regards,

Michael Milette

**Comment by cescobedo** [comment]
Hi @michael-milette,
thanks a lot for noticing this and sorry for my late response and forgot to upload the new version with the patch. Now, I've uploaded a new version 2.3 with the patch.
Thanks for your patience and help.

**Comment by michael-milette** [comment]
Thank you @cescobedo ! 🙂👍
